account-blocklist:
- 99999999999
accounts:
  '590184093698':
    filters:
      CloudTrailTrail:
      - type: regex
        value: .*
      - property: tag:DoNotNuke
        value: 'True'
      - property: tag:Permanent
        value: 'True'
      - type: regex
        value: .*auto-account-cleanser*.*
      - type: regex
        value: .*nuke-account-cleanser*.*
      - type: regex
        value: .*securityhub*.*
      - type: regex
        value: .*aws-prod*.*
      - invert: 'true'
        property: CreationDate
        type: dateOlderThan
        value: 24h
      EC2:
      - property: tag:DoNotNuke
        value: 'True'
      - property: tag:Permanent
        value: 'True'
      - type: regex
        value: .*auto-account-cleanser*.*
      - type: regex
        value: .*nuke-account-cleanser*.*
      - type: regex
        value: .*securityhub*.*
      - type: regex
        value: .*aws-prod*.*
      - invert: 'true'
        property: CreationDate
        type: dateOlderThan
        value: 24h
      IAMRole:
      - AWSReservedSSO_AWSAdministratorAccess_6a5fd71758a00e3c
      - AWSReservedSSO_AWSPowerUserAccess_889d8cf477352b37
      - AWSReservedSSO_AWSReadOnlyAccess_eb1283723d7b3eae
      - AWSReservedSSO_AWSServiceCatalogAdminFullAccess_c72788771644886c
      - AWSReservedSSO_AWSServiceCatalogEndUserAccess_14c8cd043fa1cc15
      - AWSReservedSSO_AWSAdministratorAccess_6a5fd71758a00e3c
      - AWSReservedSSO_AWSPowerUserAccess_889d8cf477352b37
      - AWSReservedSSO_AWSReadOnlyAccess_eb1283723d7b3eae
      - AWSReservedSSO_AWSServiceCatalogAdminFullAccess_c72788771644886c
      - AWSReservedSSO_AWSServiceCatalogEndUserAccess_14c8cd043fa1cc15
      IAMUser:
      - admin
      - type: regex
        value: .*
      - property: tag:DoNotNuke
        value: 'True'
      - property: tag:Permanent
        value: 'True'
      - type: regex
        value: .*auto-account-cleanser*.*
      - type: regex
        value: .*nuke-account-cleanser*.*
      - type: regex
        value: .*securityhub*.*
      - type: regex
        value: .*aws-prod*.*
      - invert: 'true'
        property: CreationDate
        type: dateOlderThan
        value: 24h
      IAMUserAccessKey:
      - property: UserName
        value: admin
      - property: tag:DoNotNuke
        value: 'True'
      - property: tag:Permanent
        value: 'True'
      - type: regex
        value: .*auto-account-cleanser*.*
      - type: regex
        value: .*nuke-account-cleanser*.*
      - type: regex
        value: .*securityhub*.*
      - type: regex
        value: .*aws-prod*.*
      - invert: 'true'
        property: CreationDate
        type: dateOlderThan
        value: 24h
      IAMUserPolicyAttachment:
      - property: RoleName
        value: admin
      - property: tag:DoNotNuke
        value: 'True'
      - property: tag:Permanent
        value: 'True'
      - type: regex
        value: .*auto-account-cleanser*.*
      - type: regex
        value: .*nuke-account-cleanser*.*
      - type: regex
        value: .*securityhub*.*
      - type: regex
        value: .*aws-prod*.*
      - invert: 'true'
        property: CreationDate
        type: dateOlderThan
        value: 24h
      S3Bucket:
      - s3://my-bucket
      - property: tag:DoNotNuke
        value: 'True'
      - property: tag:Permanent
        value: 'True'
      - type: regex
        value: .*auto-account-cleanser*.*
      - type: regex
        value: .*nuke-account-cleanser*.*
      - type: regex
        value: .*securityhub*.*
      - type: regex
        value: .*aws-prod*.*
      - invert: 'true'
        property: CreationDate
        type: dateOlderThan
        value: 24h
      SNSTopic:
      - type: regex
        value: .*
      - property: tag:DoNotNuke
        value: 'True'
      - property: tag:Permanent
        value: 'True'
      - type: regex
        value: .*auto-account-cleanser*.*
      - type: regex
        value: .*nuke-account-cleanser*.*
      - type: regex
        value: .*securityhub*.*
      - type: regex
        value: .*aws-prod*.*
      - invert: 'true'
        property: CreationDate
        type: dateOlderThan
        value: 24h
      SQSQueue:
      - property: tag:DoNotNuke
        value: 'True'
      - property: tag:Permanent
        value: 'True'
      - type: regex
        value: .*auto-account-cleanser*.*
      - type: regex
        value: .*nuke-account-cleanser*.*
      - type: regex
        value: .*securityhub*.*
      - type: regex
        value: .*aws-prod*.*
      - invert: 'true'
        property: CreationDate
        type: dateOlderThan
        value: 24h
regions:
- us-east-1
- global
resource-types:
  excludes:
  - S3Object
  - DynamoDBTableItem
  targets:
  - IAMUser
  - IAMUserPolicyAttachment
  - IAMUserAccessKey
  - S3Bucket
  - SNSTopic
  - SQSQueue
  - CloudTrailTrail
  - EC2
