regions:
  - us-east-1
  - 'global'

account-blocklist: 
  - 99999999999 # optional: restrict nuking to these accounts
  
resource-types:
  excludes: # exclude this as will be already handled when you include S3Bucket/DynamoDBTable. Else takes a lot of time and logs get filled up
  - S3Object
  - DynamoDBTableItem
  targets:
  - IAMUser
  - IAMUserPolicyAttachment
  - IAMUserAccessKey
  - S3Bucket
  - SNSTopic
  - SQSQueue
  - CloudTrailTrail

accounts:
  ACCOUNT: # will be overridden during run time based on account param
    filters:
      IAMUser:
      - "admin"
      - type: regex
        value: ".*"
      IAMUserPolicyAttachment:
      - property: RoleName
        value: "admin"
      IAMUserAccessKey:
      - property: UserName
        value: "admin"
      # CloudTrailTrail: # filter all CloudTrail
      # - type: regex
      #   value: ".*"